CUSTOM_LIBS := libraries

ARDUINO_LIBS += SPI
ARDUINO_LIBS += FastLED
ARDUINO_LIBS += FastLED_NeoMatrix
ARDUINO_LIBS += Framebuffer_GFX
ARDUINO_LIBS += Adafruit-GFX
ARDUINO_LIBS += LEDMatrix

BUILD_ROOT := build
include ../../makeNativeArduino.mk
